<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY7TUcxT\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY7TUcxT/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerY7TUcxT.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerY7TUcxT\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerY7TUcxT\appAppKernelProdContainer([
    'container.build_hash' => 'Y7TUcxT',
    'container.build_id' => '8d31a9f2',
    'container.build_time' => 1697445179,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY7TUcxT');
