<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container62Zcm23\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container62Zcm23/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container62Zcm23.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container62Zcm23\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container62Zcm23\appAppKernelDevDebugContainer([
    'container.build_hash' => '62Zcm23',
    'container.build_id' => '16f7b9e2',
    'container.build_time' => 1697445555,
], __DIR__.\DIRECTORY_SEPARATOR.'Container62Zcm23');
